export const BITCOIN_PURCHASE_TYPE = 'BITCOIN_PURCHASE_TYPE'
export const ADD_TRANSACTION = 'ADD_TRANSACTION'

export const BITCOIN_SET_COINS = 'BITCOIN_SET_COINS'
export const INVESTMENT_SET = 'INVESTMENT_SET'

export const TRANSACTION_SET_START_DATE = 'TRANSACTION_SET_START_DATE'
export const TRANSACTION_SET_END_DATE = 'TRANSACTION_SET_END_DATE'

export const SET_CURRENT_BITCOIN_PRICE = 'SET_CURRENT_BITCOIN_PRICE'

export const RESET_ALL = 'RESET_ALL'